root: true
extends:
  - plugin:@mysticatea/es2018

rules:
  # tsc does.
  "no-redeclare": "off"
  # https://github.com/typescript-eslint/typescript-eslint/issues/743
  "@mysticatea/ts/unbound-method": "off"
